# Uncomment the next line to define a global platform for your project
  platform :ios, '10.3'

target 'SnapchatCamera' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapchatCamera
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'

  target 'SnapchatCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
